// src/views/Page/contributeur/contributeur.vue
<template>
    <TitleBox colorBackground="#57c18b" typetitle="full white" title="Tu te soucies de réduire l'impact environnemental et social des solutions numériques ?"
        subtitle="Rejoins ecoCode et contribue à faire du numérique un domaine plus durable.">
        <div style=" background-color: #57c18b;" class="block-button-section-1">
            <ButtonBlock @click="scroll()" style="padding-bottom: 50px;" typebutton="white" link="#newsletter" text="Je rejoins la communauté"></ButtonBlock>
        </div>
    </TitleBox>
    <TitleBox typetitle="blue black light" title="ecoCode est un projet qui tire sa force du collectif">
        <div class="container-list">
            <span class="container-title">Les profils des contributrices et contributeurs :</span>
            <ul>
                <li><img width="24" height="24" src="@/assets/img/icon/arrow-dev.webp">Salariées et salariés en poste avec
                    un temps dédié par leur organisation sur ecoCode </li>
                <li><img width="24" height="24" src="@/assets/img/icon/arrow-dev.webp">Indépendantes et indépendants pour
                    une contribution bénévole à l'Open Source
                </li>
                <li><img width="24" height="24" src="@/assets/img/icon/arrow-dev.webp">Salariées et salariés sur leur temps
                    libre...</li>
            </ul>
        </div>
        <span class="titleSimple">Les technologies couvertes par ecoCode (en attendant d’aller plus loin !)</span>
        <BoxTechno></BoxTechno>
    </TitleBox>
    <GraphStep />
    <Newsletter id="newsletter"></Newsletter>
</template>
<script setup lang="ts">
import BoxTechno from '@/components/global/BoxTechno.vue';
import TitleBox from '@/components/global/Title.vue';
import ButtonBlock from '@/components/global/Button.vue';
import Newsletter from '@/components/global/Newsletter.vue';
import GraphStep from '@/components/Shared/GraphStep.vue';

const scroll=() => {
      const element = document.getElementById('newsletter');
      if (element) {
        element.scrollIntoView({ behavior: 'smooth' });
      }
    }
</script>
<style lang="scss" scoped>@import './scss/style.scss'</style>

// src/routes/contributeur/+page.svelte
<script>
  import LogoPython from "../../lib/assets/img/logo/logo-python.jpg";
  import LogoJava from "../../lib/assets/img/logo/logo-java.jpg";
  import LogoPhp from "../../lib/assets/img/logo/logo-php.jpg";
  import LogoJs from "../../lib/assets/img/logo/logo-js.jpg";
  import LogoHtml from "../../lib/assets/img/logo/logo-html.jpg";
  import LogoRust from "../../lib/assets/img/logo/logo-rust.jpg";
  import LogoTs from "../../lib/assets/img/logo/logo-ts.jpg";
  import LogoXml from "../../lib/assets/img/logo/logo-xml.jpg";
  import LogoAndroid from "../../lib/assets/img/logo/logo-android.jpg";
  import LogoIos from "../../lib/assets/img/logo/logo-ios.jpg";

  import IconLeft from "../../lib/assets/img/icon/arrow-left.webp";
  import IconRight from "../../lib/assets/img/icon/arrow-right.webp";

  import IconDev from "../../lib/assets/img/icon/arrow-dev.webp";

  import IconRightBlue from "../../lib/assets/img/icon/arrow-right-blue.webp";
  import IconLeftBlue from "../../lib/assets/img/icon/arrow-left-blue.webp";
  import IconBottomBlue from "../../lib/assets/img/icon/arrow-bottom-blue.webp";

  import IconLeftWhite from "../../lib/assets/img/icon/arrow-left-white.webp";
  import IconRightWhite from "../../lib/assets/img/icon/arrow-right-white.webp";
</script>

<main>
  <div class="section-01">
    <h1 class="title-accueil">
      Tu te soucies de réduire l&apos;impact environnemental et social des
      solutions numériques ?
    </h1>
    <span class="subtitle-accueil"
      >Rejoins ecoCode et contribue à faire du numérique un domaine plus
      durable.</span
    >
    <a href="/" class="button-section-02"
      ><img width="160" height="71.84" alt="Fleche Gauche" src={IconLeft} /> Je
      rejoins la communauté
      <img width="160" height="71.84" alt="Fleche Droite" src={IconRight} /></a
    >
  </div>

  <div class="section-02">
    <h2 class="title-section-02">
      Les profils des contributrices et contributeurs
    </h2>
    <span class="subtitle-section-02"
      >ecoCode est un projet qui tire sa force du collectif ! Tout le monde y
      est le bienvenu.</span
    >
    <span class="title-list-section-02"
      >Les différents types de profils actuellement impliqués sur ecoCode :</span
    >
    <div class="list-section-02">
      <div class="line-list-section-02">
        <img width="160" height="71.84" alt="Icon Dev Liste" src={IconDev} />
        <span class="text-list-section-02"
          >Salariées et salariés en poste avec un temps dédié par leur
          organisation sur ecoCode</span
        >
      </div>
      <div class="line-list-section-02">
        <img width="160" height="71.84" alt="Icon Dev Liste" src={IconDev} />
        <span class="text-list-section-02"
          >Indépendantes et indépendants pour une contribution bénévole à l'Open
          Source</span
        >
      </div>
      <div class="line-list-section-02">
        <img width="160" height="71.84" alt="Icon Dev Liste" src={IconDev} />
        <span class="text-list-section-02"
          >Salariées et salariés sur leur temps libre...</span
        >
      </div>
    </div>

    <span class="text-section-02"
      >Nos technologies (en attendant d’aller plus loin !)</span
    >

    <div class="display-techn-section-02">
      <div class="top-display-section-02">
        <img
          width="160"
          height="71.84"
          alt="logo python"
          class="img-techn-section-02"
          src={LogoPython}
        />
        <img
          width="160"
          height="71.84"
          alt="logo Java"
          class="img-techn-section-02"
          src={LogoJava}
        />
        <img
          width="160"
          height="71.84"
          alt="logo php"
          class="img-techn-section-02"
          src={LogoPhp}
        />
        <img
          width="160"
          height="71.84"
          alt="logo JS"
          class="img-techn-section-02"
          src={LogoJs}
        />
        <img
          width="160"
          height="71.84"
          alt="logo html"
          class="img-techn-section-02"
          src={LogoHtml}
        />
        <img
          width="160"
          height="71.84"
          alt="logo rust"
          class="img-techn-section-02"
          src={LogoRust}
        />
        <img
          width="160"
          height="71.84"
          alt="logo ts"
          class="img-techn-section-02"
          src={LogoTs}
        />
        <img
          width="160"
          height="71.84"
          alt="logo xml"
          class="img-techn-section-02"
          src={LogoXml}
        />
        <img
          width="160"
          height="71.84"
          alt="logo android"
          class="img-techn-section-02"
          src={LogoAndroid}
        />
        <img
          width="160"
          height="71.84"
          alt="logo ios"
          class="img-techn-section-02"
          src={LogoIos}
        />
      </div>
    </div>
  </div>

  <div class="section-03">
    <span class="title-section-03">En savoir plus sur ecoCode ?</span>
    <div class="container-box-section-03">
      <div class="box-section-3">
        <h2 class="number-section-03">1</h2>
        <span class="title-box-section-03">Renseigne ton email</span>
        <a href="/" class="button-section-03"
          ><img width="160" height="71.84" alt="Fleche Gauche" src={IconLeft} />
          Ton email ?
          <img
            width="160"
            height="71.84"
            alt="Fleche Droite"
            src={IconRight}
          /></a
        >
      </div>

      <div class="box-section-3">
        <h2 class="number-section-03">2</h2>
        <span class="title-box-section-03"
          >Reçois par email toutes les informations pour devenir contributeur</span
        >
        <a href="/" class="button-section-03"
          ><img width="160" height="71.84" alt="Fleche Gauche" src={IconLeft} />
          Je m’inscris
          <img
            width="160"
            height="71.84"
            alt="Fleche Droite"
            src={IconRight}
          /></a
        >
      </div>

      <div class="box-section-3">
        <h2 class="number-section-03">3</h2>
        <span class="title-box-section-03">Contribue à ecoCode</span>
        <a href="/" class="button-section-03"
          ><img width="160" height="71.84" alt="Fleche Gauche" src={IconLeft} />
          Allons-y !
          <img
            width="160"
            height="71.84"
            alt="Fleche Droite"
            src={IconRight}
          /></a
        >
      </div>
    </div>
  </div>

  <div class="section-04">
    <h2 class="title-section-04">Les étapes pour contribuer à ecoCode</h2>
    <div class="schema-section-04">
      <div class="top-schema-section-04">
        <div class="box-schema-section-04">
          <div class="box-int-schema-section-04">
            <div class="int-box-schema-section-04">Rejoindre GitHub</div>
            <img
              width="160"
              height="71.84"
              alt="Fleche Droite"
              id="hidden-mobile"
              class="icon-arrow-section-04"
              src={IconRightBlue}
            />
          </div>
          <img
            width="160"
            height="71.84"
            alt="Fleche vers le bas"
            id="hidden-desktop"
            class="icon-arrow-bottom-section-04"
            src={IconBottomBlue}
          />
        </div>

        <div class="box-schema-section-04">
          <div class="box-int-schema-section-04">
            <div class="int-box-schema-section-04">
              Se positionner sur un ou plusieurs répertoires en fonction du
              langage
            </div>
            <img
              width="160"
              height="71.84"
              alt="Fleche Droite"
              id="hidden-mobile"
              class="icon-arrow-section-04"
              src={IconRightBlue}
            />
          </div>
          <img
            width="160"
            height="71.84"
            alt="Fleche vers le bas"
            id="hidden-desktop"
            class="icon-arrow-bottom-section-04"
            src={IconBottomBlue}
          />
        </div>

        <div class="box-schema-section-04">
          <div class="box-int-schema-section-04">
            <div class="int-box-schema-section-04">
              S’approprier les code smells sur lesquels se baser pour écrire les
              règles
            </div>
          </div>
          <img
            width="160"
            height="71.84"
            alt="fleche vers le bas"
            class="icon-arrow-bottom-section-04"
            src={IconBottomBlue}
          />
        </div>
      </div>

      <div class="bottom-schema-section-04">
        <div class="box-schema-section-04">
          <div class="box-int-schema-section-04">
            <div class="int-box-schema-section-04">
              Intégration définitive à la solution open source ecoCode
            </div>
            <img
              width="160"
              height="71.84"
              alt="fleche gauche"
              id="hidden-mobile"
              class="icon-arrow-section-04"
              src={IconLeftBlue}
            />
          </div>
        </div>

        <div class="box-schema-section-04">
          <div class="box-int-schema-section-04">
            <div class="int-box-schema-section-04">
              Validation des règles par une Core Team
            </div>
            <img
              width="160"
              height="71.84"
              alt="fleche gauche"
              id="hidden-mobile"
              class="icon-arrow-section-04"
              src={IconLeftBlue}
            />
          </div>
          <img
            width="160"
            height="71.84"
            alt="fleche vers le bas"
            id="hidden-desktop"
            class="icon-arrow-bottom-section-04"
            src={IconBottomBlue}
          />
        </div>

        <div class="box-schema-section-04">
          <div class="box-int-schema-section-04">
            <div class="int-box-schema-section-04">
              Ecriture des règles de détection Sonar
            </div>
          </div>
          <img
            width="160"
            height="71.84"
            alt="fleche vers le bas"
            id="hidden-desktop"
            class="icon-arrow-bottom-section-04"
            src={IconBottomBlue}
          />
        </div>
      </div>
    </div>
  </div>

  <div class="section-05">
    <h2 class="title-section-05">Rejoins ecoCode !</h2>
    <span class="subtitle-section-05"
      >Rejoins-nous et contribue à faire du numérique un domaine plus durable.</span
    >
    <input class="input-section-05" type="text" placeholder="Ton e-mail" />
    <a href="/" class="button-section-05"
      ><img
        width="160"
        height="71.84"
        alt="fleche gauche"
        src={IconLeftWhite}
      />
      Recevoir les informations
      <img
        width="160"
        height="71.84"
        alt="fleche droite"
        src={IconRightWhite}
      /></a
    >
  </div>
</main>

<style>
  @import "../../lib/assets/css/contributeur.css";
  @import "../../lib/assets/css/responsive-contributeur.css";
</style>
