// src/views/Page/entreprise/entreprise.vue
<template>
    <TitleBox colorBackground="#5374c9" typetitle="white black"
        title="Nous proposons aux organisations la création de règles d'éco-conception logicielle sur-mesure."
        subtitle="En collaborant avec nous, vous réduisez votre impact numérique et contribuez à l'Open Source.">
        <div style="padding-bottom: 50px;" class="block-button-section-1">
            <ButtonBlock typebutton="white" link="/" text="Demande de contact"></ButtonBlock>
            <ButtonBlock  typebutton="white" link="/" text="Recevez le cas client Société Générale"></ButtonBlock>
        </div>
    </TitleBox>
    <TitleBox style="padding-bottom: 50px;" typetitle="title blue" title="Notre offre"
        subtitle="Nous créons des extensions SonarQube pour analyser votre code et vous permettre de réduire son impact.">
    </TitleBox>
    <Block3 title="Le processus de création d'une règle"></Block3>
    <TitleBox style="padding-bottom: 50px;" typetitle="title blue" title="Recevez notre cas client Société Générale par mail">
        <Form></Form>
    </TitleBox>
</template>
<script setup lang="ts">
import TitleBox from '@/components/global/Title.vue';
import Block3 from '@/components/Shared/Block3.vue';
import ButtonBlock from '@/components/global/Button.vue';
import Form from '@/components/Shared/FormSecond.vue';
</script>
<style lang="scss" scoped>
@import './scss/style.scss';
</style>

// src/routes/entreprise/+page.svelte
<script>
  import IconLeft from "../../lib/assets/img/icon/arrow-left.webp";
  import IconRight from "../../lib/assets/img/icon/arrow-right.webp";

  import IconLeftWhite from "../../lib/assets/img/icon/arrow-left-white.webp";
  import IconRightWhite from "../../lib/assets/img/icon/arrow-right-white.webp";
</script>

<main>
  <div class="section-01">
    <h1 class="title-accueil">
      Nous proposons aux entreprises et aux organisations la créations de règles
      d'éco-conception logicielle sur-mesure.
    </h1>
    <span class="subtitle-accueil"
      >En collaborant avec nous, vous réduisez votre impact numérique et
      contribuez à l'Open Source.</span
    >
    <div class="container-button-section-01">
      <div class="left-section-01">
        <a href="/" class="button-section-01"
          ><img alt="fleche gauche" src={IconLeft} /> Demande de contact
          <img alt="fleche droite" src={IconRight} /></a
        >
      </div>
      <div class="right-section-01">
        <a href="/" class="button-section-01"
          ><img alt="fleche gauche" src={IconLeft} /> Recevez le cas client
          Société Générale <img alt="fleche droite" src={IconRight} /></a
        >
      </div>
    </div>
  </div>

  <div class="section-02">
    <h2 class="title-section-02">
      Le processus de création d'une règle ecoCode
    </h2>
    <div class="schema-section-02">
      <div class="top-schema-section-02">
        <div class="box-schema-section-02">
          <span class="title-schema-box-section-02">Cadrage</span>
          <div class="box-int-schema-section-02">
            <div class="int-box-schema-section-02">
              Définition des règles à produire et contractualisation
            </div>
          </div>
        </div>

        <div class="box-schema-section-02">
          <span class="title-schema-box-section-02">production</span>
          <div class="box-int-schema-section-02">
            <div class="int-box-schema-section-02">
              Production des règles par notre équipe interne
            </div>
          </div>
        </div>

        <div class="box-schema-section-02">
          <span
            id="lastTitle-box-schema-section-02"
            class="title-schema-box-section-02">Test</span
          >
          <div class="box-int-schema-section-02">
            <div class="int-box-schema-section-02">
              Test des règles produites pour s’assurer de leur efficacité dans
              la réduction de la consommation énergétique
            </div>
          </div>
        </div>

        <div class="bottom-schema-section-02">
          <div class="box-schema-section-02">
            <span class="title-schema-box-section-02">Livraison</span>
            <div class="box-int-schema-section-02">
              <div class="int-box-schema-section-02">
                Mise à disposition des règles pour vos équipes
              </div>
            </div>
          </div>
        </div>
      </div>
      <span class="text-detail-schema-section-02"
        >Toutes les règles sur-mesure, produites pour le compte d'organisations,
        tombent dans l'Open Source. C'est votre contribution à rendre le
        numérique plus responsable.</span
      >
    </div>

    <div class="section-03">
      <h2 class="title-section-03">Notre offre</h2>
      <span class="subtitle-section-03"
        >Nous créons des extensions SonarQube pour analyser votre code et vous
        permettre de réduire son impact.</span
      >
      <h2 class="title-section-03">Exemple de règles produites</h2>
      <a href="/" class="button-section-03"
        ><img alt="fleche gauche" src={IconLeftWhite} /> Demande de devis
        <img alt="fleche droite" src={IconRightWhite} /></a
      >
      <h2 class="title-section-03">Exemple de règles produites</h2>
    </div>

    <div class="section-04">
      <h2 class="title-section-04">
        Recevez notre cas client Société Générale par mail
      </h2>
      <form class="form-section-04">
        <div class="form-input-section-04">
          <div class="merge-input-section-04">
            <input class="input-section-04" type="text" placeholder="Nom" />
            <input class="input-section-04" type="text" placeholder="Prénom" />
          </div>
          <input
            class="input-section-04"
            type="text"
            placeholder="Votre organisation"
          />
          <input
            class="input-section-04"
            type="text"
            placeholder="Votre rôle"
          />
          <div class="merge-input-section-04">
            <input
              class="input-section-04"
              type="text"
              placeholder="Téléphone"
            />
            <input class="input-section-04" type="text" placeholder="E-mail" />
          </div>
          <textarea
            class="text-area-section-04"
            type="text"
            placeholder="Votre besoin"
          />
        </div>
      </form>

      <a href="/" class="button-section-04"
        ><img alt="fleche gauche" src={IconLeftWhite} /> Recevez notre cas
        client <img alt="fleche droite" src={IconRightWhite} /></a
      >
    </div>
  </div>
</main>

<style>
  @import "../../lib/assets/css/entreprise.css";
  @import "../../lib/assets/css/responsive-entreprise.css";
</style>
