// src/routes/footer.svelte
<footer>
  <span class="text-footer">Started with 💚 in France in 2019</span>
</footer>

<style>
  footer {
    height: 60px;
    background-color: white;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
  }

  .text-footer {
    font-family: "Mulish", sans-serif;
    font-weight: bold;
    font-style: italic;
  }
</style>

// src/components/global/Footer.vue
<template>
    <footer>
        <span class="text-footer">Started with 💚 in France in 2019</span>
      </footer>
</template>
<script setup lang="ts">

</script>

<style lang="scss" scoped>
footer {
    height: 60px;
    background-color: white;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
  }

  .text-footer {
    font-family: "Mulish", sans-serif;
    font-weight: bold;
    font-style: italic;
  }
</style>
